name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build with Maven (run tests)
        run: ./mvnw -B -q -DskipTests=false verify
